"use client";

import './globals.css'
import { Lexend, Unbounded } from 'next/font/google'
import { Nav } from './nav';
import { Footer } from './footer';

const lexend = Lexend({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
})

const unbounded = Unbounded({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-unbounded',
})

export const metadata = {
  title: 'Clover | Timeless Design',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${unbounded.variable} ${lexend.variable}`}>
      <body>
        <Nav />
        {/* Pages Routes */}
        {children}
        <Footer />
      </body>
    </html>
  )
}
