import './globals.css'
import { Lexend, Unbounded } from 'next/font/google'

export const metadata = {
  title: 'Clover | Timeless Design',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
